# If enabled, HackedServer will send a fake forge handshake to your users
# in order to retrieve the forge mod list sent by forge clients
enabled = true

[category]

[category.whitelisted]
color = "<green>"
mods = [
    "FML",
    "FORGE",
    "MCP",
    "MINECRAFT",
    "MERCURIUS_UPDATER",
    "BETTERFOLIAGE"
]

[category.blacklisted]
color = "<red>"
mods = [
    "FORGEWURST",
    "FORGEHAX",
    "WURST"
]